### ISSUE TITLE
patient_overview_report and overview_reports appear to be duplicates

### ISSUE THREAD

**Issue by aghaynes** [SwissClinicalTrialOrganisation/DM_secuTrial_recipes#25]

**Comment by aghaynes** [comment]
Maybe one can be changed to actually running the reports rather than defining them?

**Comment by PatrickRWright** [comment]
Whoops, I thought I had deleted that. I will fix that later. Thank you for noticing.

**Comment by aghaynes** [comment]
It also doesnt seem to be in the repo level readme, although I might have missed it...

**Comment by PatrickRWright** [comment]
I removed the duplicate.
