### ISSUE TITLE
annotated eCRF

### ISSUE THREAD

**Issue by aghaynes** [SwissClinicalTrialOrganisation/DM_secuTrial_recipes#3]
Might be useful to add how to create annotated eCRFs (could be an extension to the print CRF one perhaps)

**Comment by PatrickRWright** [comment]
Are you or someone else from Bern keen to add the extension?

**Comment by aghaynes** [comment]
I can't - no access to the relevant part of SecuTrial. I doubt that anyone
with the appropriate access knows anything about github...

**Comment by PatrickRWright** [comment]
We can get them involved. Part of my presentation on the meeting on Thursday will involve some github intro also with a specific focus on how to write such recipes. Can you share this information in Bern to make sure that the according people join in?

**Comment by aghaynes** [comment]
I just made a pull request with an annotated CRFs section. I'll send an email to the DMs here to try and encourage them to attend the session tomorrow.
